# Using lightweight docker image for node
FROM node:20-alpine as base

# Set the working directory
WORKDIR /usr/src/backend-app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the source code
COPY . .

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]